### ISSUE TITLE
Reading Clarius DICOM Files

### ISSUE THREAD

**Issue by benjaminralex** [clariusdev/cad#6]
Hello, I am currently trying to read in the dicom file in MATLAB using dicomread(), but get the following error about encoding:

"Data encoding for transfer syntax UID "1.2.840.10008.1.2.4.80" not supported."

Any suggestions here? Attaching the dcm acquired using Clarius.

**Comment by clariusk** [comment]
please contact support@clarius.com, as this repository is for usage of the clarius CAD design models, thank you.
